### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by rodopoulos1** [Source2ZE/MultiAddonManager#7] opened 2024-04-12 00:21 UTC
Server is crashing when change map to load models on plugins

![image](https://github.com/Source2ZE/MultiAddonManager/assets/101236856/0ca04e34-6b7b-41fa-b66e-eda60270a096)

Version 1.2.5

**Comment by xLeviNx** [comment] 2024-04-12 09:51
Your error does not show anything unique or different that relates to this being the cause of the crash.

**Comment by brkvlr** [comment] 2024-04-14 10:52
I think I have the same problem, my server started to crash when the map changed after the workshop downlaod was completed.

**Comment by rodopoulos1** [comment] 2024-04-14 15:15
Hey Levin, when i remove multiaddonmanager i can change mao normally so the problem is on multiaddonmanager

**Comment by rodopoulos1** [comment] 2024-04-17 12:45
The addons on the server are downloaded by the server and client. Its working normally. Only when i changes the map the crash appear. I will show printscreen when i get home

**Comment by rodopoulos1** [comment] 2024-04-17 19:59
here is a image from my cfg:

![image](https://github.com/Source2ZE/MultiAddonManager/assets/101236856/afcfc9cc-5c55-4eab-a34f-90259019d159)

Contact me on discord and we can test, when a plugin change the map server crashes, and addons are working but when change map crash

Discord: Rodopoulos

**Comment by daffyyyy** [comment] 2024-05-04 19:03
![image](https://github.com/Source2ZE/MultiAddonManager/assets/41084667/da5ee516-5ced-430e-aa5a-f16b1f21109c)
Sometimes after map change

**Comment by Vauff** [comment] 2024-10-06 23:56
I believe this ended up being a CS# precaching crash that was fixed by https://github.com/roflmuffin/CounterStrikeSharp/commit/2eaf7c2d8c7ab0810ed87756ac5f6c1cf6d756e4, so I will close this.

If this is still an issue, please make a new issue, and include a [AcceleratorCS2](https://github.com/Source2ZE/AcceleratorCS2) crashdump link, as just "Segmentation fault" in these screenshots does not actually tell us anything meaningful.

**Closed by Vauff** 2024-10-06 23:56 UTC
